receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "localhost:4317"
      http:
        endpoint: "localhost:4318"

exporters:
  debug:
    verbosity: detailed

  otlphttp/grafana:
    endpoint: ${otlp_endpoint}
    headers:
      Authorization: ${otlp_header_authorization}

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/grafana,debug]
    metrics:
      receivers: [otlp]
      exporters: [otlphttp/grafana,debug]
    logs:
      receivers: [otlp]
      exporters: [otlphttp/grafana,debug]
